apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: sentiment-analysis
  labels:
    app: flask-app
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 020866158197.dkr.ecr.ap-south-1.amazonaws.com/sentiment-analysis-project:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: CAPSTONE_TEST

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: sentiment-analysis
  labels:
    app: flask-app
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000